# -*- coding: utf-8 -*-
"""sentiment Analysis.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Q9MOTVcZSQqB79650OnQ1se29i_wrWC
"""

pip install nltk textblob pandas

import re
import pandas as pd
import nltk
from textblob import TextBlob

# Download necessary NLTK corpora (only once)
nltk.download('punkt')
# Function to clean tweet
def clean_tweet(tweet):
    tweet = re.sub(r'http\S+|www\S+|https\S+', '', tweet, flags=re.MULTILINE)  # remove URLs
    tweet = re.sub(r'\@\w+|\#','', tweet)  # remove mentions and hashtags
    tweet = re.sub(r'[^\w\s]', '', tweet)  # remove punctuation
    tweet = re.sub(r'\d+', '', tweet)      # remove numbers
    tweet = tweet.lower().strip()          # lower and strip
    return tweet
# Function to get sentiment

def get_sentiment(tweet):
    analysis = TextBlob(tweet)
    polarity = analysis.sentiment.polarity
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'
# Load or define your data

data = {
    'tweet': [
        "I love the new design of the iPhone!",
        "This is the worst update ever. I hate it!",
        "I’m not sure how I feel about the new changes.",
        "Absolutely fantastic customer service. Well done!",
        "The app keeps crashing. Very frustrating.",
        "Nothing special, just an average experience.",
        "Can't complain, it works fine."
    ]
}

df = pd.DataFrame(data)

df['cleaned_tweet'] = df['tweet'].apply(clean_tweet)
df['sentiment'] = df['cleaned_tweet'].apply(get_sentiment)

# Display results
print(df[['tweet', 'sentiment']])